export const types = Object.freeze({
    USERS_START_FETCHING: 'USERS_START_FETCHING',
    USERS_STOP_FETCHING: 'USERS_STOP_FETCHING',
    USERS_FILL: 'USERS_FILL',
    USERS_SET_FETCHING_ERROR: 'USERS_SET_FETCHING_ERROR',
    USERS_FETCH_ASYNC: 'USERS_FETCH_ASYNC'
  });